linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - revive
    - gosimple
    - staticcheck
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - unconvert
    - unused
run:
  timeout: 30m

linters-settings:
  gosec:
    excludes:
      - G401
      - G501
