before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - id: cm
    main: ./cmd/chall-manager
    binary: chall-manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -cover
  - id: cmj
    main: ./cmd/chall-manager-janitor
    binary: chall-manager-janitor
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -cover

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

source:
  enabled: true

checksum: {}

sboms:
  - artifacts: source
