version: 2

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - id: cm
    main: ./cmd/chall-manager
    binary: chall-manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -cover
    ldflags:
      - -s -w
      - -X github.com/ctfer-io/chall-manager/cmd/chall-manager.Version={{.Version}}
      - -X github.com/ctfer-io/chall-manager/cmd/chall-manager.Commit={{.Commit}}
      - -X github.com/ctfer-io/chall-manager/cmd/chall-manager.Date={{.Date}}
      - -X github.com/ctfer-io/chall-manager/cmd/chall-manager.BuiltBy=goreleaser

  - id: cmj
    main: ./cmd/chall-manager-janitor
    binary: chall-manager-janitor
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -cover
    ldflags:
      - -s -w
      - -X github.com/ctfer-io/chall-manager/cmd/chall-manager-janitor.Version={{.Version}}
      - -X github.com/ctfer-io/chall-manager/cmd/chall-manager-janitor.Commit={{.Commit}}
      - -X github.com/ctfer-io/chall-manager/cmd/chall-manager-janitor.Date={{.Date}}
      - -X github.com/ctfer-io/chall-manager/cmd/chall-manager-janitor.BuiltBy=goreleaser

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

source:
  enabled: true

checksum: {}

sboms:
  - artifacts: source
