# Build stage
FROM golang:1.24.0@sha256:2b1cbf278ce05a2a310a3d695ebb176420117a8cfcfcc4e5e68a1bef5f6354da AS builder

WORKDIR /go/src
COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0
RUN go build -cover -o /go/bin/chall-manager-janitor cmd/chall-manager-janitor/main.go



# Prod stage
FROM scratch
COPY --from=builder /go/bin/chall-manager-janitor /chall-manager-janitor
ENTRYPOINT [ "/chall-manager-janitor" ]
