FROM pulumi/pulumi-go:3.144.1
RUN pulumi login --local
COPY chall-manager /chall-manager
COPY ./gen/api/v1/launch/launch.swagger.json ./gen/api/v1/launch/launch.swagger.json
ENTRYPOINT [ "/chall-manager" ]
