// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/v1/instance/instance.proto

package instance

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The challenge identifier
	ChallengeId string `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// The source (user/team) identifier.
	SourceId string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// A key=value additional configuration to pass to the instance when created.
	Additional    map[string]string `protobuf:"bytes,3,rep,name=additional,proto3" json:"additional,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceRequest) Reset() {
	*x = CreateInstanceRequest{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceRequest) ProtoMessage() {}

func (x *CreateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInstanceRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *CreateInstanceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *CreateInstanceRequest) GetAdditional() map[string]string {
	if x != nil {
		return x.Additional
	}
	return nil
}

type RetrieveInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The challenge identifier
	ChallengeId string `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// The source (user/team) identifier.
	SourceId      string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveInstanceRequest) Reset() {
	*x = RetrieveInstanceRequest{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveInstanceRequest) ProtoMessage() {}

func (x *RetrieveInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveInstanceRequest.ProtoReflect.Descriptor instead.
func (*RetrieveInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{1}
}

func (x *RetrieveInstanceRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *RetrieveInstanceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type QueryInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source (user/team) identifier.
	SourceId      string `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryInstanceRequest) Reset() {
	*x = QueryInstanceRequest{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInstanceRequest) ProtoMessage() {}

func (x *QueryInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryInstanceRequest.ProtoReflect.Descriptor instead.
func (*QueryInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{2}
}

func (x *QueryInstanceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type RenewInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The challenge identifier
	ChallengeId string `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// The source (user/team) identifier.
	SourceId      string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewInstanceRequest) Reset() {
	*x = RenewInstanceRequest{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewInstanceRequest) ProtoMessage() {}

func (x *RenewInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewInstanceRequest.ProtoReflect.Descriptor instead.
func (*RenewInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{3}
}

func (x *RenewInstanceRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *RenewInstanceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type DeleteInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The challenge identifier
	ChallengeId string `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// The source (user/team) identifier.
	SourceId      string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInstanceRequest) Reset() {
	*x = DeleteInstanceRequest{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstanceRequest) ProtoMessage() {}

func (x *DeleteInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeleteInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteInstanceRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *DeleteInstanceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

// The challenge instance object that the chall-manager exposes.
// Notice it differs from the internal representation, as it handles
// filesystem-related information.
type Instance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The challenge identifier
	ChallengeId string `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// The source (user/team) identifier.
	SourceId string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// The time since when the instance is running.
	Since *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`
	// The last time the instance has been renewed.
	LastRenew *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_renew,json=lastRenew,proto3" json:"last_renew,omitempty"`
	// The time the instance will "die" i.e. be destroyed by the janitor.
	Until *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=until,proto3,oneof" json:"until,omitempty"`
	// The connection information that is given to the players in order
	// to reach their instance.
	ConnectionInfo string `protobuf:"bytes,6,opt,name=connection_info,json=connectionInfo,proto3" json:"connection_info,omitempty"`
	// If specified, the flag that validates the challenge instance.
	// This avoids shareflag, but don't block sharing solving strategy/write-up.
	// DEPRECATED: #950 showed the need for multiple flags, so please migrate to it.
	//
	// Deprecated: Marked as deprecated in api/v1/instance/instance.proto.
	Flag *string `protobuf:"bytes,7,opt,name=flag,proto3,oneof" json:"flag,omitempty"`
	// A list of flags that validates the challenge instance.
	// This avoids shareflag, but don't block sharing solving strategy/write-up.
	Flags []string `protobuf:"bytes,9,rep,name=flags,proto3" json:"flags,omitempty"`
	// A key=value additional configuration to pass to the instance when created.
	Additional    map[string]string `protobuf:"bytes,8,rep,name=additional,proto3" json:"additional,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{5}
}

func (x *Instance) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *Instance) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Instance) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *Instance) GetLastRenew() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRenew
	}
	return nil
}

func (x *Instance) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *Instance) GetConnectionInfo() string {
	if x != nil {
		return x.ConnectionInfo
	}
	return ""
}

// Deprecated: Marked as deprecated in api/v1/instance/instance.proto.
func (x *Instance) GetFlag() string {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return ""
}

func (x *Instance) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *Instance) GetAdditional() map[string]string {
	if x != nil {
		return x.Additional
	}
	return nil
}

var File_api_v1_instance_instance_proto protoreflect.FileDescriptor

const file_api_v1_instance_instance_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/v1/instance/instance.proto\x12\x0fapi.v1.instance\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x8c\x02\n" +
	"\x15CreateInstanceRequest\x12-\n" +
	"\fchallenge_id\x18\x01 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\vchallengeId\x12'\n" +
	"\tsource_id\x18\x02 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\bsourceId\x12\\\n" +
	"\n" +
	"additional\x18\x03 \x03(\v26.api.v1.instance.CreateInstanceRequest.AdditionalEntryB\x04\xe2A\x01\x01R\n" +
	"additional\x1a=\n" +
	"\x0fAdditionalEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\x17RetrieveInstanceRequest\x12-\n" +
	"\fchallenge_id\x18\x01 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\vchallengeId\x12'\n" +
	"\tsource_id\x18\x02 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\bsourceId\"?\n" +
	"\x14QueryInstanceRequest\x12'\n" +
	"\tsource_id\x18\x01 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\bsourceId\"n\n" +
	"\x14RenewInstanceRequest\x12-\n" +
	"\fchallenge_id\x18\x01 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\vchallengeId\x12'\n" +
	"\tsource_id\x18\x02 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\bsourceId\"o\n" +
	"\x15DeleteInstanceRequest\x12-\n" +
	"\fchallenge_id\x18\x01 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\vchallengeId\x12'\n" +
	"\tsource_id\x18\x02 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\bsourceId\"\xc5\x04\n" +
	"\bInstance\x12-\n" +
	"\fchallenge_id\x18\x01 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\vchallengeId\x12'\n" +
	"\tsource_id\x18\x02 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\bsourceId\x12<\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\x05since\x12E\n" +
	"\n" +
	"last_renew\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\tlastRenew\x12A\n" +
	"\x05until\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\x92A\x03J\x011\xe2A\x01\x01H\x00R\x05until\x88\x01\x01\x123\n" +
	"\x0fconnection_info\x18\x06 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\x0econnectionInfo\x12%\n" +
	"\x04flag\x18\a \x01(\tB\f\x92A\x03J\x011\xe2A\x01\x01\x18\x01H\x01R\x04flag\x88\x01\x01\x12\x1a\n" +
	"\x05flags\x18\t \x03(\tB\x04\xe2A\x01\x01R\x05flags\x12O\n" +
	"\n" +
	"additional\x18\b \x03(\v2).api.v1.instance.Instance.AdditionalEntryB\x04\xe2A\x01\x01R\n" +
	"additional\x1a=\n" +
	"\x0fAdditionalEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_untilB\a\n" +
	"\x05_flag2\x95\x05\n" +
	"\x0fInstanceManager\x12p\n" +
	"\x0eCreateInstance\x12&.api.v1.instance.CreateInstanceRequest\x1a\x19.api.v1.instance.Instance\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/instance\x12\x8c\x01\n" +
	"\x10RetrieveInstance\x12(.api.v1.instance.RetrieveInstanceRequest\x1a\x19.api.v1.instance.Instance\"3\x82\xd3\xe4\x93\x02-\x12+/api/v1/instance/{challenge_id}/{source_id}\x12m\n" +
	"\rQueryInstance\x12%.api.v1.instance.QueryInstanceRequest\x1a\x19.api.v1.instance.Instance\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/instance0\x01\x12\x89\x01\n" +
	"\rRenewInstance\x12%.api.v1.instance.RenewInstanceRequest\x1a\x19.api.v1.instance.Instance\"6\x82\xd3\xe4\x93\x020:\x01*2+/api/v1/instance/{challenge_id}/{source_id}\x12\x85\x01\n" +
	"\x0eDeleteInstance\x12&.api.v1.instance.DeleteInstanceRequest\x1a\x16.google.protobuf.Empty\"3\x82\xd3\xe4\x93\x02-*+/api/v1/instance/{challenge_id}/{source_id}B<Z:github.com/ctfer-io/chall-manager/api/v1/instance;instanceb\x06proto3"

var (
	file_api_v1_instance_instance_proto_rawDescOnce sync.Once
	file_api_v1_instance_instance_proto_rawDescData []byte
)

func file_api_v1_instance_instance_proto_rawDescGZIP() []byte {
	file_api_v1_instance_instance_proto_rawDescOnce.Do(func() {
		file_api_v1_instance_instance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_instance_instance_proto_rawDesc), len(file_api_v1_instance_instance_proto_rawDesc)))
	})
	return file_api_v1_instance_instance_proto_rawDescData
}

var file_api_v1_instance_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_v1_instance_instance_proto_goTypes = []any{
	(*CreateInstanceRequest)(nil),   // 0: api.v1.instance.CreateInstanceRequest
	(*RetrieveInstanceRequest)(nil), // 1: api.v1.instance.RetrieveInstanceRequest
	(*QueryInstanceRequest)(nil),    // 2: api.v1.instance.QueryInstanceRequest
	(*RenewInstanceRequest)(nil),    // 3: api.v1.instance.RenewInstanceRequest
	(*DeleteInstanceRequest)(nil),   // 4: api.v1.instance.DeleteInstanceRequest
	(*Instance)(nil),                // 5: api.v1.instance.Instance
	nil,                             // 6: api.v1.instance.CreateInstanceRequest.AdditionalEntry
	nil,                             // 7: api.v1.instance.Instance.AdditionalEntry
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 9: google.protobuf.Empty
}
var file_api_v1_instance_instance_proto_depIdxs = []int32{
	6,  // 0: api.v1.instance.CreateInstanceRequest.additional:type_name -> api.v1.instance.CreateInstanceRequest.AdditionalEntry
	8,  // 1: api.v1.instance.Instance.since:type_name -> google.protobuf.Timestamp
	8,  // 2: api.v1.instance.Instance.last_renew:type_name -> google.protobuf.Timestamp
	8,  // 3: api.v1.instance.Instance.until:type_name -> google.protobuf.Timestamp
	7,  // 4: api.v1.instance.Instance.additional:type_name -> api.v1.instance.Instance.AdditionalEntry
	0,  // 5: api.v1.instance.InstanceManager.CreateInstance:input_type -> api.v1.instance.CreateInstanceRequest
	1,  // 6: api.v1.instance.InstanceManager.RetrieveInstance:input_type -> api.v1.instance.RetrieveInstanceRequest
	2,  // 7: api.v1.instance.InstanceManager.QueryInstance:input_type -> api.v1.instance.QueryInstanceRequest
	3,  // 8: api.v1.instance.InstanceManager.RenewInstance:input_type -> api.v1.instance.RenewInstanceRequest
	4,  // 9: api.v1.instance.InstanceManager.DeleteInstance:input_type -> api.v1.instance.DeleteInstanceRequest
	5,  // 10: api.v1.instance.InstanceManager.CreateInstance:output_type -> api.v1.instance.Instance
	5,  // 11: api.v1.instance.InstanceManager.RetrieveInstance:output_type -> api.v1.instance.Instance
	5,  // 12: api.v1.instance.InstanceManager.QueryInstance:output_type -> api.v1.instance.Instance
	5,  // 13: api.v1.instance.InstanceManager.RenewInstance:output_type -> api.v1.instance.Instance
	9,  // 14: api.v1.instance.InstanceManager.DeleteInstance:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_v1_instance_instance_proto_init() }
func file_api_v1_instance_instance_proto_init() {
	if File_api_v1_instance_instance_proto != nil {
		return
	}
	file_api_v1_instance_instance_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_instance_instance_proto_rawDesc), len(file_api_v1_instance_instance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_instance_instance_proto_goTypes,
		DependencyIndexes: file_api_v1_instance_instance_proto_depIdxs,
		MessageInfos:      file_api_v1_instance_instance_proto_msgTypes,
	}.Build()
	File_api_v1_instance_instance_proto = out.File
	file_api_v1_instance_instance_proto_goTypes = nil
	file_api_v1_instance_instance_proto_depIdxs = nil
}
