name: E2E tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'deploy/go.mod'

      - name: Set up Docker registry
        run: |
          docker network create kind || true
          docker run -d --network kind --name registry -p 5000:5000 registry:2

      - name: Write config file
        run: |
          cat <<EOF > kind-config.yaml
          apiVersion: kind.x-k8s.io/v1alpha4
          kind: Cluster
          containerdConfigPatches:
          - |
            [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
              endpoint = ["http://registry:5000"]
          
          kubeadmConfigPatches:
          - |
            kind: ClusterConfiguration
            apiServer:
              extraArgs:
                "service-node-port-range": "30000-30005"

          nodes:
          - role: control-plane
            extraPortMappings:
            - containerPort: 30000
              hostPort: 30000
            - containerPort: 30001
              hostPort: 30001
            - containerPort: 30002
              hostPort: 30002
            - containerPort: 30003
              hostPort: 30003
            - containerPort: 30004
              hostPort: 30004
            - containerPort: 30005
              hostPort: 30005
          networking:
            disableDefaultCNI: true
          EOF

      - name: Set up Kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # 1.12.0
        with:
          config: kind-config.yaml
          cluster_name: kind
        env:
          KIND_EXPERIMENTAL_DOCKER_NETWORK: kind

      - name: Patch local-path to mount shared filesystem path on the single kind node
        run: |
          # From https://github.com/kubernetes-sigs/kind/issues/1487#issuecomment-2211072952
          kubectl -n local-path-storage patch configmap local-path-config -p '{"data": {"config.json": "{\n\"sharedFileSystemPath\": \"/var/local-path-provisioner\"\n}"}}'

      - name: Setup Cilium as Kind CNI
        run: |
          # See https://docs.cilium.io/en/stable/installation/kind/#install-cilium
          helm repo add cilium https://helm.cilium.io/

          docker pull quay.io/cilium/cilium:v1.17.4
          kind load docker-image quay.io/cilium/cilium:v1.17.4

          helm install cilium cilium/cilium --version 1.17.4 \
            --namespace kube-system \
            --set image.pullPolicy=IfNotPresent \
            --set ipam.mode=kubernetes

      - name: Export server URL
        id: server
        run: |
          echo "server=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' kind-control-plane)" >> "$GITHUB_OUTPUT"

      - name: Build and push CM
        run: |
          docker build \
              -t localhost:5000/ctferio/chall-manager:${{ github.sha }} \
              -f Dockerfile.chall-manager \
              .
          docker push localhost:5000/ctferio/chall-manager:${{ github.sha }}

      - name: Build and push CMJ
        run: |
          docker build \
              -t localhost:5000/ctferio/chall-manager-janitor:${{ github.sha }} \
              -f Dockerfile.chall-manager-janitor \
              .
          docker push localhost:5000/ctferio/chall-manager-janitor:${{ github.sha }}

      - name: Load Docker images
        run: |
          docker pull bitnami/etcd:3.5.16-debian-12-r0 && docker tag $_ localhost:5000/$_ && docker push $_
          docker pull library/busybox:1.28             && docker tag $_ localhost:5000/$_ && docker push $_

      - name: Install Pulumi
        uses: pulumi/actions@cc7494be991dba0978f7ffafaf995b0449a0998e # v6.5.0
      - name: Prepare environment
        run: |
          pulumi login --local

      # The following steps cleans up the GHA ubuntu environment.
      # It is required due to Pulumi consuming large space when starting a prod-like
      # environment for Integration Tests purposes.
      # It removes around 25 Gib of disk space.
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false # keep everything around here to avoid shoothing kind and local registry

      - name: Romeo environment
        id: env
        uses: ctfer-io/romeo/environment@f0943c42d2affd7b572890a2784b2e63be58b7e1 # v0.2.0
        with:
          kubeconfig: ~/.kube/config
          storage-class-name: standard
          pvc-access-mode: ReadWriteOnce
          harden: true

      - name: Run E2E Tests
        run: |
          go test -v ./deploy/integration/ -run=^Test_I_ -coverprofile=integration.cov -timeout=30m
          go test -v ./deploy/integration/ -run=^Test_T_ -coverprofile=technical.cov -timeout=30m
        env:
          NAMESPACE: ${{ steps.env.outputs.namespace }}
          REGISTRY: localhost:5000
          TAG: ${{ github.sha }}
          ROMEO_CLAIM_NAME: ${{ steps.env.outputs.claim-name }}
          SERVER: ${{ steps.server.outputs.server }}

      - name: Download Romeo results
        id: download
        uses: ctfer-io/romeo/download@f0943c42d2affd7b572890a2784b2e63be58b7e1 # v0.2.0
        with:
          server: http://${{ steps.server.outputs.server }}:${{ steps.env.outputs.port }}

      - name: Merge coverage data
        run: |
          # Point back to the actual Go module tested.
          # It cannot be inferred, leading to this highly precise step.
          sed -i 's|^/go/src|github.com/ctfer-io/chall-manager|' ${{ steps.download.outputs.path }}

          go install go.shabbyrobe.org/gocovmerge/cmd/gocovmerge@fa4f82cfbf4d57c646c1ed0f35002bf1b89fbf7a
          gocovmerge integration.cov technical.cov ${{ steps.download.outputs.path }} > e2e.cov

      - name: Upload e2e tests coverage
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: e2e.cov
          path: e2e.cov
